/* WARNING: This file is automatically generated. Do not edit. */

typedef struct {
	uint8_t service_index;
	uint8_t att_index;
	const char *name;
	const char *type;
} char_name_table;

#define service_count 0
#define char_name_count 0
#define max_attribute_count 0

static const uint8_t attribute_counts[0] = {};
static const esp_gatts_attr_db_t gatt_db[0][0] = {};
static const char_name_table char_names[0] = {};
