/* WARNING: This file is automatically generated. Do not edit. */

export default Object.freeze({
	"tls": {
	"DHE_RSA": true,
	"ECDHE_RSA": true
},
	"file": {
	"root": "/mod/"
},
	"format": "RGB565LE",
	"rotation": 0,
}, true);
