/* WARNING: This file is automatically generated. Do not edit. */

#define MODDEF_I2C_SDA_PIN (21)
#define MODDEF_I2C_SCL_PIN (22)
#define MODDEF_XS_MODS (1)
#define PIU_DASH_SIGNATURE "tech-moddable-host"
#define PIU_DOT_SIGNATURE "tech.moddable.host"
#define PIU_SLASH_SIGNATURE "/tech/moddable/host"
